#!/bin/bash
# compile all the Game components as class files for dependency adding
#for f in ../../src/Game/*.java; do javac -cp ../../java-json.jar:../../bin -d ../../bin "$f"; done
javac -cp ../../java-json.jar:../../bin -d ../../bin ../../src/Game/Zombie.java ../../src/Game/RuleCheckerAdversary.java ../../src/Game/RuleCheckerPlayer.java ../../src/Game/IRuleChecker.java ../../src/Game/IRuleChecker.java ../../src/Game/ICharacter.java ../../src/Game/GameManager.java ../../src/Game/Ghost.java ../../src/Game/GameStatus.java ../../src/Game/IAdversary.java ../../src/Game/Player.java ../../src/Game/Hallway.java ../../src/Game/Position.java ../../src/Game/Room.java ../../src/Game/Level.java ../../src/Common/IUser.java ../../src/Common/IObserver.java ../../src/User/LocalUser.java ../../src/Observer/LocalObserver.java > NUL

javac -cp ../../java-json.jar:../../bin -d ../../bin ../../src/Level/TestLevel.java


# make class file for testing suite, create jar file, then execute program
javac -cp ../../java-json.jar:../../bin -d ../../bin ../../src/Manager/TestManager.java > NUL
jar cfm testManager.jar ../../MANIFESTMANAGER.MF -C ../../bin/ Manager/TestManager.class
java -jar ./testManager.jar

rm NUL
rm testManager.jar
