#!/bin/bash
# compile all the Game components as class files for dependency adding
javac -cp ../../java-json.jar:../../bin -d ../../bin ../../src/Game/Adversary.java ../../src/Game/Player.java ../../src/Game/Hallway.java ../../src/Game/Position.java ../../src/Game/Room.java ../../src/Game/Level.java > NUL

# make class file for testing suite, create jar file, then execute program
javac -cp ../../java-json.jar:../../bin -d ../../bin ../../src/Level/TestLevel.java > NUL
jar cfm testlevel.jar ../../MANIFESTLEVEL.MF -C ../../bin/ Level/TestLevel.class
java -jar ./testlevel.jar

rm NUL
rm testlevel.jar